name: SQL Dev

on:
  push:
    branches:
      - develop
    paths:
      - "DDL/**"
      - "DML/**"
      - "filelist.txt"
      - "executa-sql.sh"

jobs:
  migrate:
    runs-on: ubuntu-latest

    environment: dev 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install PostgreSQL client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Make script executable
        run: chmod +x executa-sql.sh

      - name: Run SQL scripts
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: ./executa-sql.sh
